### ISSUE TITLE
Consider adding spot color support for the VT240, VT340

### ISSUE THREAD

**Issue by hackerb9** [forth2020/frenchie68#4]
Another possibly bad idea: The VT340 could display 16 colors simultaneously, but (as far as I know) that was only for sixel or ReGIS _graphics_. It did not support _text_ color through the simple "ANSI color" escape sequences.  However, it is possible to get one additional text color by displaying characters as bold (`Esc` `[` `1` `m`) and redefining what "bold" means. ReGIS graphics shared the same color palette as the text, so one could change entry number 15 to change bold text. 

For example, 

    echo $'\eP0p S( M 15 (H 0 L 49 S 59 ) )\e\\'

would set "bold" to blue (hue angle 0°, lightness 49%, saturation 59%). 

If one made the maze blue, it might look more interesting. As a benefit, the same code will probably work on a VT240 and be ignored by a VT420, except showing the maze as brighter.

_____

By the way, the other text styles are affected by the ReGIS palette as well, but they are not as useful:

| Text Style      | Color Index | Used as color for | VT340 Default |
|------------|-------------|-------------------|---------------|
| Background | 0           | Background screen | Black         |
| Foreground | 7           | Normal text       | Medium gray   |
| Bright     | 15          | Bold text         | Light gray    |
| Blink      | 8           | Blink+Bold text   | Dark gray     |

Since the Blink color actually blinks on the screen, it could be used for the Power Pills which are supposed to flash.

**Comment by frenchie68** [comment]
Hello Hacker9b,

I would love to support the features you mentioned. That would be utterly cool. Alas I have no physical device to test this in the field. I know how to query the target terminal identity and maybe I should make sure it is a VT420 before I go any further.

By the way, your mediacopy script cannot work on the VT420 because the device's setup menu does not support a sixel printer at all. The code clearly specifies that the scope of the implementation is limited to the VT420 and I am not in the habit of releasing code I haven't personally tested before.

All the best.

        Francois

**Comment by hackerb9** [comment]
Thank you for even considering it. ☺
